# Script to generate review feedback samples CSV
import pandas as pd

# Sample review texts for each sentiment category
positive_reviews = [
    "Excellent service! Staff was very helpful and quick processing.",
    "Fast transaction, friendly staff. Will come back again.",
    "Very efficient branch. No long waiting time today.",
    "Staff explained everything clearly. Great customer service!",
    "Quick and professional service. Highly recommended branch.",
    "Clean facility, organized queue system. Very satisfied.",
    "Teller was courteous and processed my request quickly.",
    "No hassle transaction. Staff was accommodating.",
    "Great branch! Modern facilities and efficient service.",
    "Outstanding customer service. Staff went above and beyond.",
    "Very fast processing. Impressed with the service quality.",
    "Friendly atmosphere, helpful staff. Five stars!",
    "Smooth transaction from start to finish. Well done!",
    "Professional staff, clean environment. Excellent experience.",
    "Quick service despite busy day. Thank you for good service.",
    "Efficient tellers, minimal wait time. Very pleased.",
    "Staff was patient in explaining loan details. Great service!",
    "Modern branch with excellent customer service standards.",
    "Fast and accurate processing. Keep up the good work!",
    "Wonderful experience! Staff made banking easy and convenient.",
    "Love this branch! Super fast service 👍",
    "Best bank staff ever! Always smiling",
    "Quick and easy. No complaints!",
    "Amazing customer service today",
    "Fast tellers, clean bathrooms lol",
    "Staff remembered my name. Sweet!",
    "5 stars! Will definitely return",
    "Parking was easy, service quick",
    "No wait time today. Perfect!",
    "Friendly faces everywhere",
    "ATM worked perfectly fine",
    "Great location, helpful people",
    "Smooth transaction as always",
    "Professional and courteous staff",
    "Clean facility, organized setup",
    "Amazing digital banking features! Mobile app works flawlessly.",
    "Best bank in the area. Never had any issues with their service.",
    "Loan approval was surprisingly fast. Great rates too!",
    "Staff remembered my name and preferences. Personal touch appreciated.",
    "Open on weekends which is very convenient for working people.",
    "Security measures are top-notch. Feel safe banking here.",
    "Investment advice was spot on. Made good returns this year.",
    "Credit card application processed same day. Impressive!",
    "Drive-thru service is super convenient. Never have to get out.",
    "Online banking platform is user-friendly and secure.",
    "Mortgage team was incredibly helpful throughout the process.",
    "24/7 customer service actually works! Got help at midnight.",
    "Interest rates are competitive. Happy with my savings account.",
    "Branch manager personally handled my complaint. Excellent!",
    "Free ATM usage worldwide saved me hundreds in fees.",
    "Financial planning session was informative and helpful.",
    "Quick business account setup. Got everything done in one visit.",
    "Student account benefits are amazing. No fees at all!",
    "Insurance products are reasonably priced and comprehensive.",
    "Mobile check deposit feature saves so much time.",
    "Wealth management team exceeded my expectations completely.",
    "Foreign exchange rates are better than competitors.",
    "Home loan pre-approval process was smooth and transparent.",
    "Senior citizen benefits are generous and well-designed.",
    "Credit score monitoring service is a great value-add.",
    "Fraud protection caught suspicious activity immediately.",
    "Business banking solutions perfectly fit our company needs.",
    "Refinancing process was hassle-free with great new rates.",
    "Investment portfolio performance has been consistently strong.",
    "Customer loyalty program rewards are actually worthwhile.",
    "Branch renovation looks modern and welcoming now.",
    "Educational workshops on financial literacy were excellent.",
    "Personalized financial advice helped me plan better.",
    "Quick response to account security concerns. Very professional.",
    "Debt consolidation loan helped me get back on track.",
    "Premium banking services justify the additional fees.",
    "Auto loan rates were the best I found anywhere.",
    "Tax preparation service saved me time and money.",
    "Trust and estate planning services are comprehensive.",
    "Corporate banking team understands our business needs perfectly."
]

negative_reviews = [
    "Very long waiting time. Poor queue management system.",
    "Unfriendly staff, slow service. Need improvement urgently.",
    "Waited over 30 minutes for simple transaction. Terrible.",
    "Rude teller, unprofessional behavior. Very disappointed.",
    "System always down, wasting customer's time. Fix it!",
    "Crowded branch, insufficient staff. Need more tellers.",
    "Poor customer service. Staff seems uninterested to help.",
    "Long lines every day. Need better crowd management.",
    "Slow processing, outdated systems. Time to upgrade.",
    "Staff lacks proper training. Made errors in transaction.",
    "Terrible experience. Will switch to another branch.",
    "Air conditioning not working. Hot and uncomfortable.",
    "Website says open but branch was closed. Poor communication.",
    "ATM always broken. Need better machine maintenance.",
    "Complicated procedures, unhelpful staff. Frustrating experience.",
    "Waited 1 hour for loan processing. Completely unacceptable.",
    "Staff talking personal matters while serving. Very unprofessional.",
    "No proper social distancing. Safety protocols ignored.",
    "Parking area too small. Always full, very inconvenient.",
    "Computer system slow. Every transaction takes forever.",
    "Waited 45 mins for nothing. Ridiculous!",
    "Rude staff. Never coming back.",
    "System crashed AGAIN. Get it together!",
    "Worst branch ever. Zero stars",
    "Staff ignoring customers completely",
    "Long lines every single day",
    "ATM ate my card. Great.",
    "Unprofessional behavior from manager",
    "Parking lot is a nightmare",
    "Always understaffed. Always.",
    "Slow as molasses. Ugh.",
    "Made me wait to close my account",
    "Fees everywhere! Money grab",
    "No one knows what they're doing",
    "Terrible customer service training",
"Hidden fees everywhere! Not transparent about charges at all.",
    "Mobile app crashes constantly. Technology is terrible here.",
    "Loan application rejected without proper explanation. Frustrating!",
    "Account was frozen due to their system error. Nightmare experience.",
    "Interest rates on savings are practically zero. Waste of time.",
    "Customer service puts you on hold for hours. Unacceptable!",
    "ATM ate my card and branch couldn't help immediately.",
    "Online banking security questions are ridiculously complicated.",
    "Overdraft fees are excessive and unreasonable. Money grab!",
    "Branch closes too early. Not convenient for working people.",
    "Credit card interest rates increased without proper notice.",
    "Investment advice lost me money. Questionable recommendations.",
    "Mortgage application process took months with endless paperwork.",
    "Staff turnover is high. Always dealing with new people.",
    "Parking fees at downtown branch are outrageous addition.",
    "Wire transfer fees are much higher than other banks.",
    "Business account monthly fees keep increasing every year.",
    "Insurance products are overpriced compared to direct providers.",
    "Foreign transaction fees are hidden until you travel.",
    "Safe deposit box rental doubled without explanation.",
    "Automatic payment system failed multiple times this year.",
    "Branch merger caused chaos with account numbers changing.",
    "Wealth management advisor was pushy and unprofessional.",
    "Check clearing times are unreasonably long in digital age.",
    "Credit score monitoring service has outdated information.",
    "Fraud department declined legitimate purchases repeatedly.",
    "Small business loan requirements are impossibly strict.",
    "Refinancing was denied despite improved credit score.",
    "Investment platform is outdated and hard to navigate.",
    "Loyalty program rewards expired without notification.",
    "Construction noise makes banking visits unpleasant experience.",
    "Financial advisor pushed expensive products unnecessarily.",
    "Identity verification process is overly complicated and slow.",
    "Debt management advice was generic and unhelpful.",
    "Premium account benefits don't match the high fees.",
    "Auto loan approval took weeks despite pre-qualification.",
    "Tax service made errors requiring amendments and fees.",
    "Trust services communication was poor throughout process.",
    "Corporate account setup required visiting multiple departments.",
    "Account closure process was deliberately made difficult."
]

neutral_reviews = [
    "Regular service, nothing special. Average branch experience.",
    "Standard banking service. Met basic expectations.",
    "Okay service, could be better. Room for improvement.",
    "Average wait time, decent staff. Typical bank visit.",
    "Service was fine, not great but acceptable.",
    "Normal processing time. Staff did their job adequately.",
    "Standard branch operations. Nothing to complain about.",
    "Fair service quality. Expected better but okay overall.",
    "Decent facilities, average customer service. It's okay.",
    "Regular bank experience. No major issues encountered.",
    "Standard procedures followed. Nothing remarkable happened.",
    "Average branch, typical banking service provided.",
    "Acceptable service level. Staff was professional enough.",
    "Normal banking experience. No surprises, good or bad.",
    "Fair processing time. Service was satisfactory overall.",
    "Standard bank branch. Met minimum service expectations.",
    "Regular transaction completed. Nothing special to note.",
    "Average customer service. Staff was polite but busy.",
    "Typical bank visit. Service was adequate for needs.",
    "Standard operating procedures. Everything went normally.",
    "It's a bank. Does bank things.",
    "Service was okay. Nothing special.",
    "Average wait time, decent staff",
    "Could be better, could be worse",
    "Standard banking experience here",
    "Gets the job done, I guess",
    "Meh. It's fine for basic stuff",
    "Not great, not terrible either",
    "Regular branch. No surprises.",
    "Fair service, fair prices",
    "Adequate for my banking needs",
    "Pretty standard bank branch",
    "No complaints, no compliments",
    "Did what I needed done",
    "Typical bank experience",
    "Banking here for 5 years. No major complaints or praise.",
    "Services are comparable to other banks in the area.",
    "Digital features work but could use some improvements.",
    "Staff follows procedures but lacks enthusiasm for service.",
    "Interest rates are market standard, nothing special offered.",
    "Branch location is convenient but parking can be challenging.",
    "Customer service resolves issues but takes standard time.",
    "Fees are transparent but wish they were lower overall.",
    "Mobile app functions adequately for basic banking needs.",
    "Loan process was by-the-book, no surprises either way.",
    "ATM network coverage is decent in most areas.",
    "Investment options are limited but cover basic needs.",
    "Security measures seem adequate for today's standards.",
    "Business banking services meet our basic requirements.",
    "Credit card terms are standard for the industry.",
    "Online banking works fine most of the time.",
    "Branch hours are typical for banks in this region.",
    "Staff knowledge varies depending on who you get.",
    "Account management tools are functional but dated.",
    "Customer communication could be more proactive overall.",
    "Mortgage rates were competitive when I applied last year.",
    "Financial planning services are basic but cover essentials.",
    "Wait times vary greatly depending on day and time.",
    "Product offerings are standard for mid-sized regional bank.",
    "Technology updates happen but seem to lag behind competitors.",
    "Branch amenities are basic - coffee, water, comfortable seating.",
    "Processing times are average, neither fast nor slow.",
    "Account statements are clear and easy to understand.",
    "Customer portal has essential features but nothing innovative.",
    "Support team is polite and follows standard procedures.",
    "Banking products meet needs but don't exceed expectations.",
    "Fees are disclosed upfront but add up over time.",
    "Services delivered as promised, nothing more or less.",
    "Branch staff is professional but not particularly memorable.",
    "Systems work reliably most of the time with occasional issues.",
    "Policies are clearly stated and consistently applied.",
    "Facilities are clean and functional, standard bank environment.",
    "Response times to inquiries are reasonable for industry.",
    "Account features are sufficient for personal banking needs.",
    "Overall experience is predictable and meets basic expectations."
]

# Create DataFrame
review_data = {
    'sentiment': ['positive'] * 75 + ['negative'] * 75 + ['neutral'] * 75,
    'review_text': positive_reviews + negative_reviews + neutral_reviews
}

df = pd.DataFrame(review_data)

# Save to CSV
df.to_csv('bpi_review_samples.csv', index=False)
print("✅ Review samples saved to 'bpi_review_samples.csv'")
print(f"Total samples: {len(df)} ({len(positive_reviews)} positive, {len(negative_reviews)} negative, {len(neutral_reviews)} neutral)")
print("\nFirst few samples:")
print(df.head())