# Manual branch mapping for difficult cases
# Generated branch name -> Main sheet branch name

MANUAL_BRANCH_MAPPING = {
    'BPI St. Luke\'s Branch': 'St. Luke\'s',
    'BPI T Sora - Visayas Avenue Branch': 'T Sora - Visayas Avenue',
    'BPI Tandang Sora Branch': 'Tandang Sora',
    'BPI Timog Avenue Branch': 'Timog Avenue',
    'BPI Timog Circle Branch': 'Timog Circle',
    'BPI Trinoma Branch': 'Trinoma',
    'BPI Trinoma North Branch': 'Trinoma North',
    'BPI U.P. Techno Hub Branch': 'U.P. Techno Hub',
    'BPI UP Town Center Branch': 'Up Town Center',
    'BPI Visayas Avenue Branch': 'Visayas Avenue',
    'BPI Waltermart North EDSA Branch': 'Waltermart North EDSA',
    'BPI West Avenue Del Monte Branch': 'West Ave. - Del Monte',
    'BPI Xavierville Branch': 'Xavierville',
    'BPI Eastwood City Branch': 'Eastwood City',
    'BPI SM North EDSA Branch': 'SM North EDSA',
    'BPI GLOBE BGC Branch': 'Globe BGC',
    'BPI Infinity Branch': 'Infinity',
    'BPI Market Market Branch': 'Market Market',
    'BPI W5Th Avenue BGC Branch': 'W5Th Avenue BGC',
    'BPI Diego Silang - Petron C5 Branch': 'Diego Silang - Petron C5',
    'BPI FTI Taguig Branch': 'FTI Taguig',
    'BPI Fort Bonifacio Bayani Road Branch': 'Fort Bonifacio Bayani Road',
    'BPI Fort Mckinley Hill Branch': 'Fort Mckinley Hill',
    'BPI Fort Serendra Branch': 'Fort Serendra',
    'BPI Marulas Branch': 'Marulas',
    'BPI Valenzuela Paso De Blas Branch': 'Paso De Blas',
    'BPI Valenzuela Malinta Branch': 'Valenzuela Malinta',
    'BPI Valenzuela Dalandanan Branch': 'Valenzuela Dalandanan',
    'BPI One Global Place Branch': 'One Global Place',
    'BPI PSE The Fort Branch': 'PSE The Fort',
}
